- name: add nginx config to sites-available
  template: src=./nginx.conf.j2 dest=/etc/nginx/sites-available/{{ ansible_host }}
  notify:
    - restart nginx

- name: add symlink in nginx sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ ansible_host }}
    dest: /etc/nginx/sites-enabled/{{ ansible_host }}
    state: link
  notify:
    - restart nginx

- name: write gunicorn service script
  template:
    src: ./gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn-{{ ansible_host }}.service
  notify:
    - restart gunicorn