# Generated by Django 3.1.1 on 2020-09-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', unique=True)),
                ('usable_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PluginVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(default='')),
                ('language', models.TextField(default='')),
                ('is_esl', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.plugins')),
            ],
        ),
        migrations.CreateModel(
            name='WordsOfPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='SoulsGems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Scrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perks', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='IllusionSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='DestructionSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='ConjurationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='AlterationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Alchemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('version', 'language', 'instance', 'is_esl'), name='unique_variant'),
        ),
    ]
