# Generated by Django 2.2.3 on 2019-08-10 17:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0002_character_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='default_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='character',
            name='desired_skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
