# Generated by Django 2.2.3 on 2019-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0003_character_default_desired'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='desired_level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='priority_multiplier',
            field=models.FloatField(default=1.5),
        ),
    ]
