# Generated by Django 2.2.3 on 2019-08-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0004_character_desired_level_priority_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fill_skills',
            field=models.BooleanField(default=False),
        ),
    ]
