# Generated by Django 2.2.3 on 2019-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0005_character_fill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
