# Generated by Django 3.0.1 on 2020-04-09 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0007_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='plugin_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plugins',
            name='plugin_language',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plugins',
            name='plugin_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plugins',
            name='plugin_version',
            field=models.TextField(default=''),
        ),
    ]
