# Generated by Django 3.0.1 on 2020-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0008_plugin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='plugin_usable_name',
            field=models.TextField(default=''),
        ),
    ]
