# Generated by Django 3.0.1 on 2020-04-14 17:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0009_plugin_usable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugins',
            name='plugin_data',
        ),
        migrations.RemoveField(
            model_name='plugins',
            name='plugin_language',
        ),
        migrations.RemoveField(
            model_name='plugins',
            name='plugin_version',
        ),
        migrations.CreateModel(
            name='PluginVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_version', models.TextField(default='')),
                ('plugin_language', models.TextField(default='')),
                ('plugin_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('plugin_instance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.Plugins')),
            ],
        ),
    ]
