# Generated by Django 3.0.1 on 2020-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0010_variants_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('plugin_version', 'plugin_language'), name='unique_variant'),
        ),
    ]
