# Generated by Django 3.0.1 on 2020-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0012_unique_plugin_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pluginvariants',
            name='unique_variant',
        ),
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('plugin_version', 'plugin_language', 'plugin_instance'), name='unique_variant'),
        ),
    ]
