# Generated by Django 3.0.1 on 2020-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0013_unique_for_plugin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pluginvariants',
            name='unique_variant',
        ),
        migrations.RenameField(
            model_name='pluginvariants',
            old_name='plugin_instance',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='pluginvariants',
            old_name='plugin_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='pluginvariants',
            old_name='plugin_version',
            new_name='version',
        ),
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('version', 'language', 'instance'), name='unique_variant'),
        ),
    ]
