# Generated by Django 3.0.1 on 2020-05-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0015_rename_plugin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginvariants',
            name='esl',
            field=models.BooleanField(default=False),
        ),
    ]
