# Generated by Django 3.0.1 on 2020-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0016_pluginvariants_esl'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pluginvariants',
            name='unique_variant',
        ),
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('version', 'language', 'instance', 'esl'), name='unique_variant'),
        ),
    ]
