# Generated by Django 3.0.1 on 2020-05-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0017_add_esl_to_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginvariants',
            old_name='esl',
            new_name='is_esl',
        ),
    ]
