# Generated by Django 3.0.1 on 2020-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0019_rename_character_to_skills'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pluginvariants',
            name='unique_variant',
        ),
        migrations.AddConstraint(
            model_name='pluginvariants',
            constraint=models.UniqueConstraint(fields=('version', 'language', 'instance', 'is_esl'), name='unique_variant'),
        ),
    ]
