# Generated by Django 3.1a1 on 2020-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0020_fix_esl_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginvariants',
            name='plugin_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
