# Generated by Django 3.1a1 on 2020-06-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0021_change_to_django_JSONField'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
