# Generated by Django 3.1a1 on 2020-06-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0022_delete_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginvariants',
            name='plugin_data',
        ),
        migrations.CreateModel(
            name='WordsOfPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_of_power', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapons', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='SoulsGems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souls_gems', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Scrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrolls', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perks', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscellaneous', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='IllusionSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='DestructionSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='ConjurationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armors', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='AlterationSpells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Alchemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alchemy', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='the_elder_commands.pluginvariants')),
            ],
        ),
    ]
