# Generated by Django 3.1a1 on 2020-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0023_create_data_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alchemy',
            name='alchemy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='alterationspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='ammo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='armors',
            name='armors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='books',
            name='books',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conjurationspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='destructionspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='illusionspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='keys',
            name='keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='otherspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='perks',
            name='perks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='restorationspells',
            name='spells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scrolls',
            name='scrolls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='soulsgems',
            name='souls_gems',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='weapons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wordsofpower',
            name='words_of_power',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
