# Generated by Django 3.1a1 on 2020-06-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0024_default_list_allow_blank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alchemy',
            old_name='alchemy',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='ammo',
            old_name='ammo',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='armors',
            old_name='armors',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='books',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredients',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='keys',
            old_name='keys',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='miscellaneous',
            old_name='miscellaneous',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='perks',
            old_name='perks',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='scrolls',
            old_name='scrolls',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='soulsgems',
            old_name='souls_gems',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='weapons',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='wordsofpower',
            old_name='words_of_power',
            new_name='words',
        ),
    ]
