# Generated by Django 3.1a1 on 2020-06-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0025_rename_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perks',
            old_name='items',
            new_name='perks',
        ),
    ]
