# Generated by Django 3.1a1 on 2020-06-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_elder_commands', '0026_rename_perks_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordsofpower',
            old_name='words',
            new_name='spells',
        ),
    ]
